name = "realty-lander"
main = "src/worker.js"
compatibility_date = "2024-01-01"
account_id = 04366e6a18a185bcae6be03a3bd99aca

[vars]
VNOC_API_URL = "https://manage.vnoc.com"
VNOC_API_KEY  = "b102e32a4bf14b575f352186e265ed7c7272cde4ded39f0c478530f6b358c9c4"

# To deploy: wrangler deploy (from this folder)
